# if(MSVC)
#     set(CMAKE_C_FLAGS_DEBUG_INIT "/D_DEBUG /MTd")
#     set(CMAKE_C_FLAGS_MINSIZEREL_INIT     "/MT")
#     set(CMAKE_C_FLAGS_RELEASE_INIT        "/MT")
#     set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "/MT")
# endif()

